### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by RoshanGH** [beego/samples#14]
todo 项目运行后 会有一个  2017/04/19 21:10:10 [staticfile.go:61] [W] Can't find the file: static/js/angular.min.js.map stat static/js/angular.min.js.map: no such file or directory 

waring不影响运行但是，我想知道原因。谢谢

**Comment by astaxie** [comment]
看上去是你的chrome装了什么插件请求引起的

**Comment by RoshanGH** [comment]
好吧  现在又没有  重现了我在检查下  谢谢解答

**Comment by astaxie** [comment]
我刚搜索了一下关于这个错误，找到了这个http://stackoverflow.com/questions/28860416/angular-map-file-not-found

后来发现todo里面引用了angular文件，删除这一行应该就可以了

https://github.com/beego/samples/commit/d1b57d459c3ad5c7465aaa8976bf560a0cc20c08

**Comment by RoshanGH** [comment]
sourceMappingURL=angular.min.js.map

看到了  我有点强迫症 哈哈  谢谢解答
